### ISSUE TITLE
simple_app Executing packaged app locally Error

### ISSUE THREAD

**Issue by dukeyu2011** [Project-MONAI/monai-deploy-app-sdk#223] opened 2021-12-06 09:42 UTC
Hi, 

I am new to use MONAI and try the tutorial "01 simple_app" by jupyter notebook.

MAP is built successfully and I tried to run but got a error message as following.

the command i used.
# Copy a test input file to 'input' folder
!mkdir -p testinput && rm -rf input/*
!cp {test_input_path} testinput/
!ls testinput
# Launch the app
!monai-deploy run simple_app:latest testinput output

============================================================
the message i got

normal-brain-mri-4.png
Checking dependencies...
--> Verifying if "docker" is installed...

--> Verifying if "simple_app:latest" is available...

Checking for MAP "simple_app:latest" locally
"simple_app:latest" found.

Reading MONAI App Package manifest...
Going to initiate execution of operator SobelOperator
Executing operator SobelOperator (Process ID: 1, Operator ID: 896fa9c1-0fce-4ab0-a69d-cf86548bfedd)
Traceback (most recent call last):
  File "/opt/monai/app/app.py", line 22, in <module>
    App(do_run=True)
  File "/opt/conda/lib/python3.8/site-packages/monai/deploy/core/application.py", line 129, in __init__
    self.run(log_level=args.log_level)
  File "/opt/conda/lib/python3.8/site-packages/monai/deploy/core/application.py", line 429, in run
    executor_obj.run()
  File "/opt/conda/lib/python3.8/site-packages/monai/deploy/core/executors/single_process_executor.py", line 125, in run
    op.compute(op_exec_context.input_context, op_exec_context.output_context, op_exec_context)
  File "/opt/monai/app/sobel_operator.py", line 21, in compute
    input_path = next(input_path.glob("*.*"))  # take the first file
StopIteration

ERROR: MONAI Application "simple_app:latest" failed.

is there anything wrong and how to solve this, many thanks

**Comment by vikashg** [comment] 2021-12-07 16:55
working on it.

**Comment by vikashg** [comment] 2021-12-07 18:08
Hello @dukeyu2011, I am unable to reproduce the error but here are my thoughts. 
1. make sure that you have followed the [documentation](https://docs.monai.io/projects/monai-deploy-app-sdk/en/latest/getting_started/tutorials/01_simple_app.html)
2. I also tried changing the path to the input file as you mentioned but I still was able to run everything without any errors. Can you give some more information about your installation (environment/version of python etc.) In addition can you upload your input file on a google drive so we can try. 
Thanks

**Comment by dukeyu2011** [comment] 2021-12-08 05:32
@vikashg 

I used virtual box to install ubnutu 18.04, docker 20.10.11, pulling Anaconda image from https://docs.anaconda.com/anaconda/user-guide/tasks/docker/

python version is 3.6.15 in conda environment.

Followed the documentation and the following is the command I used

>    1  conda env list
>     2  conda create -n monai python=3.6 pytorch torchvision jupyterlab cudatoolkit=11.1 -c pytorch -c conda-forge
>     3  conda activate monai
>     4  git clone --branch main --depth 1 https://github.com/Project-MONAI/monai-deploy-app-sdk.git
>     5  cd monai-deploy-app-sdk
>     6  pip install monai-deploy-app-sdk
>     7  pip install scikit-image
>     8  ls
>     9  python examples/apps/simple_imaging_app/app.py -i examples/apps/simple_imaging_app/brain_mr_input.jpg -o output
>    10  ls
>    11  monai-deploy package examples/apps/simple_imaging_app -t simple_app:latest -l DEBUG
>    12  ls
>    13  mkdir -p input && rm -rf input/*
>    14  cp examples/apps/simple_imaging_app/brain_mr_input.jpg input/
>    15  monai-deploy run simple_app:latest input output
>    16  history


I got the error message as following.

> (monai) root@b1d981020f3c:/monai-deploy-app-sdk# monai-deploy run simple_app:latest input output
> Checking dependencies...
> --> Verifying if "docker" is installed...
> 
> --> Verifying if "simple_app:latest" is available...
> 
> Checking for MAP "simple_app:latest" locally
> "simple_app:latest" found.
> 
> Reading MONAI App Package manifest...
> Traceback (most recent call last):
>   File "/opt/monai/app/app.py", line 12, in <module>
>     from gaussian_operator import GaussianOperator
>   File "/opt/monai/app/gaussian_operator.py", line 12, in <module>
>     import monai.deploy.core as md
> ModuleNotFoundError: No module named 'monai'

**Comment by dbericat** [comment] 2021-12-08 14:43
It looks like it is not able to import monai. 

@dukeyu2011 did you try running the Jupyter and see if you got the same error?

@gigony probably doesn't matter, but comparing the instructions on the [Jupyter notebook](https://github.com/Project-MONAI/monai-deploy-app-sdk/blob/main/notebooks/tutorials/01_simple_app.ipynb) vs [Executing on shell](https://docs.monai.io/projects/monai-deploy-app-sdk/en/latest/getting_started/tutorials/01_simple_app.html), the only thing it stood out to me was that the notebook does this:

!python -c "import monai.deploy" || pip install -q "monai-deploy-app-sdk"

**Comment by vikashg** [comment] 2021-12-08 14:53
@dukeyu2011 If @dbericat is right, the issue can be solved by exiting the jupyter notbook using ctrl-C or ctrl-Z. At this point I believe you will be in the same monai environment (made using conda). once in this place can you execute the command
`pip install monai-deploy-app-sdk`. 
At this point start the jupyter notebook again and re run the cells. If @dbericat  is right, doing this operation should solve your problem. I will try reproducing your error later in the day. 
Keep us posted.

**Comment by dukeyu2011** [comment] 2021-12-08 15:28
@dbericat adn @vikashg  

I tried jupyter notebook and executing on shell. The error message is the same.

Another way I tried is to add  
[requirements-test.txt](https://github.com/Project-MONAI/monai-deploy-app-sdk/files/7677019/requirements-test.txt)
when I build simple_app docker. the build command is 

monai-deploy package simple_imaging_app --tag simple:latest -r requirements-test.txt

the docker is built successfully but go wrong when i run it. 

monai-deploy run simple_app:latest testinput output

============================================================
the message i got

> normal-brain-mri-4.png
> Checking dependencies...
> --> Verifying if "docker" is installed...
> 
> --> Verifying if "simple_app:latest" is available...
> 
> Checking for MAP "simple_app:latest" locally
> "simple_app:latest" found.
> 
> Reading MONAI App Package manifest...
> Going to initiate execution of operator SobelOperator
> Executing operator SobelOperator (Process ID: 1, Operator ID: 896fa9c1-0fce-4ab0-a69d-cf86548bfedd)
> Traceback (most recent call last):
> File "/opt/monai/app/app.py", line 22, in
> App(do_run=True)
> File "/opt/conda/lib/python3.8/site-packages/monai/deploy/core/application.py", line 129, in init
> self.run(log_level=args.log_level)
> File "/opt/conda/lib/python3.8/site-packages/monai/deploy/core/application.py", line 429, in run
> executor_obj.run()
> File "/opt/conda/lib/python3.8/site-packages/monai/deploy/core/executors/single_process_executor.py", line 125, in run
> op.compute(op_exec_context.input_context, op_exec_context.output_context, op_exec_context)
> File "/opt/monai/app/sobel_operator.py", line 21, in compute
> input_path = next(input_path.glob(".")) # take the first file
> StopIteration
> 
> ERROR: MONAI Application "simple_app:latest" failed.

**Comment by vikashg** [comment] 2021-12-08 20:40
`cp: cannot stat 'testinput/temp/normal-brain-mri-4.png': No such file or directory
Checking dependencies...
--> Verifying if "docker" is installed...

--> Verifying if "simple_app:latest" is available...

Checking for MAP "simple_app:latest" locally
"simple_app:latest" found.

Reading MONAI App Package manifest...
Going to initiate execution of operator SobelOperator
Executing operator SobelOperator (Process ID: 1, Operator ID: f0788193-1e95-4268-a7b2-b004b4f79b3f)
[2021-12-08 20:32:18,909] [INFO] (matplotlib.font_manager) - generated new fontManager
Traceback (most recent call last):
  File "/opt/monai/app/app.py", line 22, in <module>
    App(do_run=True)
  File "/home/monai/.local/lib/python3.8/site-packages/monai/deploy/core/application.py", line 129, in __init__
    self.run(log_level=args.log_level)
  File "/home/monai/.local/lib/python3.8/site-packages/monai/deploy/core/application.py", line 429, in run
    executor_obj.run()
  File "/home/monai/.local/lib/python3.8/site-packages/monai/deploy/core/executors/single_process_executor.py", line 125, in run
    op.compute(op_exec_context.input_context, op_exec_context.output_context, op_exec_context)
  File "/opt/monai/app/sobel_operator.py", line 21, in compute
    input_path = next(input_path.glob("*.*"))  # take the first file
StopIteration

ERROR: MONAI Application "simple_app:latest" failed.`

@dukeyu2011 and @gigony  I was able to reproduce the error by emptying the input folder. So, @dukeyu2011 I suggest that you please check the folder in which you have the test image. Probably its empty? If it is you will get this error.

**Comment by MMelQin** [comment] 2021-12-08 22:07
@dukeyu2011 You mentioned about `pulling Anaconda image from https://docs.anaconda.com/anaconda/user-guide/tasks/docker/`. Are you running conda docker as the host to run the Jupyter notebook, which also means that the example MONAI Application Package (docker) is built within a the docker, and the `monai-deploy run` would run docker within the conda docker?

**Comment by vikashg** [comment] 2021-12-08 22:10
@MMelQin Yes, another thing I forgot to mention from morning's meeting is that maybe you have the images in the folder but the directories are not mapped properly if what @MMelQin is saying is true.

**Comment by dukeyu2011** [comment] 2021-12-09 03:45
@MMelQin  adn @vikashg  thanks for your help

I have checked the input file has an example image. 

the problem might be  running conda docker as the host to run the Jupyter notebook.

Thus I installed again.  the environment is virtual box to install ubnutu 18.04, docker 20.10.11 and anaconda.

the command followed as [https://docs.monai.io/projects/monai-deploy-app-sdk/en/latest/getting_started/tutorials/01_simple_app.html](url)

MONAI image can be built successfully but got a error message when run it without more information.

![擷取](https://user-images.githubusercontent.com/5790812/145330759-bb81ce2e-b99a-4eb7-a928-0e1c6a9224ee.PNG)

**Comment by dukeyu2011** [comment] 2021-12-10 03:35
is any update or something i have to check? please let me know.

**Comment by MMelQin** [comment] 2021-12-10 06:56
I think the failure has something to do with the environment. I'll try to recap below.

- To run the example Jupyter Notebook, conda needs to be used to create and activate the conda env, called monai in the example. But with running the Notebook in the conda docker, the last couple steps in the Notebook to run the application docker failed, as running docker in another docker may not work properly. In any case, you succeeded in running the example application and getting the result before packaging and running the app in docker form.  

- When not running the Notebook, conda env is not needed. The above screenshot looks to be running in the conda env, called monai. Wonder if you want to exit/deactivate that env, and use this [guide ](https://github.com/Project-MONAI/monai-deploy-app-sdk#installation) instead.

**Comment by dukeyu2011** [comment] 2021-12-10 09:41
Hi @MMelQ  

thanks for your summary.
that are current situation and i tried in base env to run today.

the same error i got and python version is 3.9.7
![擷取](https://user-images.githubusercontent.com/5790812/145552462-6e47be0f-d461-407e-a63f-028bfe2be4c8.PNG)

**Comment by dukeyu2011** [comment] 2021-12-13 02:00
is anything I need to check? please let me know.

**Comment by MMelQin** [comment] 2021-12-14 07:31
I think by now, it is clear that executing the Python app directly works, but once the app is packaged, using `monai-deploy package` command, into MAP (Docker image), execution will `monai-deploy run` command encounters the unspecified error.
 
So, can you try to run the package app, i.e. the Docker image, in interactive mode, and then launch the app.py from within like running it on the console? e.g. (assuming in the current working dir, there is already input and output folders)
`mqin@mingq-dt:~/src/monai-app-sdk$ docker run -it --rm -v $(pwd)/input:/input -v $(pwd)/output:/output --entrypoint /bin/bash simple_app:latest`

Once in the Docker, check the `/input` folder has the input image file, and then run the `app.py`
```
monai@3bfe2e008826:/var/monai$ ls /input
brain_mr_input.jpg
monai@3bfe2e008826:/var/monai$ python /opt/monai/app/app.py -i /input -o /output
monai@3bfe2e008826:/var/monai$ ls /output
final_output.png
monai@3bfe2e008826:/var/monai$
``` 
Hope this will provide some more details.

**Comment by dukeyu2011** [comment] 2021-12-16 02:22
@MMelQin  thanks for your comments. I tried and took a snapshot for error message for your team

there are two point I founded.

1.when I run in simple:latest docker as the command, there is no jpg file in input folder. I used wget command to download from github.

2.Has monai/app folder and app.py but something error when I run app.py.

![擷取](https://user-images.githubusercontent.com/5790812/146295937-c762f1d9-a26c-4aa1-a993-c60bf8f4eeb1.PNG)

**Comment by MMelQin** [comment] 2021-12-18 08:33
Sorry I meant to respond right away, but somehow did not hit the comment button.

As seen in the console log, the SobelOperator failed with Illegal instruction (core dumped). This error cannot be reproduced running the MONAI App Package docker directly on a host machine, either interactively within the docker itself or with `monai-deploy run`. So, my hunch would be the VirtualBox VM somehow is not working well with the base image for the MAP, `nvcr.io/nvidia/pytorch:21.07-py3`, though will need to set up the env and try to reproduce. 

In the meantime, the latest tag for the pytorch image is 21.11-py, `nvcr.io/nvidia/pytorch:21.11-py3`. It can be used when packaging the MAP Docker image by adding the `-b` option,
`monai-deploy package examples/apps/simple_imaging_app -t simple_app:latest -l DEBUG -b nvcr.io/nvidia/pytorch:21.11-py3`

**Comment by MMelQin** [comment] 2022-02-09 23:41
@carolinarsm thanks for contributing!

A patch release [v0.2.1 of the MONAI Deploy App SDK](https://docs.monai.io/projects/monai-deploy-app-sdk/en/latest/release_notes/v0.2.1.html) was release to address a few issues reported and the latest change in Jupyter. In this latest version, the [inadvertent dependency on monai package for application that does not use monai had been removed](https://github.com/Project-MONAI/monai-deploy-app-sdk/pull/169/files).

**Comment by dukeyu2011** [comment] 2022-02-10 01:27
Hello guys, many thanks!

**Closed** 2022-02-25 21:45 UTC
Labels: good first issue, help wanted
